# Generated by Django 2.2.3 on 2019-07-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_auto_20190702_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroinfo',
            name='type',
            field=models.CharField(choices=[('good', '正义'), ('bad', '邪恶')], default='man', max_length=5),
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='gender',
            field=models.CharField(choices=[('man', '男'), ('woman', '女')], max_length=5),
        ),
    ]
