# Generated by Django 2.2.3 on 2019-07-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0003_auto_20190704_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroinfo',
            name='type',
            field=models.CharField(choices=[('good', '正义'), ('bad', '邪恶')], default='good', max_length=5),
        ),
    ]
