# Generated by Django 2.2.3 on 2019-07-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_auto_20190716_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(default='picture/', upload_to='picture'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='img/', upload_to='img'),
        ),
    ]
