# Generated by Django 2.2.3 on 2019-07-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0004_auto_20190716_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, default='picture/img.jpg', null=True, upload_to='picture'),
        ),
    ]
