# Generated by Django 2.2.3 on 2019-07-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0007_product_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
