# Generated by Django 2.2.3 on 2019-07-05 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20, null=True, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=40, null=True, verbose_name='密码')),
                ('register_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='注册时间')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=20, null=True)),
                ('code', models.CharField(max_length=20, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vote.Account')),
            ],
        ),
    ]
